services:
  mongodb:
    image: mongo:7.0.9
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p hoidanit-mongodb-4rn up -d
